[package]
name = "rim"
version = "0.1.0"
authors = ["kinnisvara24 <85039422+kinnisvara24@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
anyhow = "1.0.71"
ropey = "1.6.0"